layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

links:
  -
    name: 技术博客
    url: http://utensil.github.io/tech/
    icon: telescope
  -
    name: 文字博客
    url: http://utensil.github.io/writings/
    icon: book

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  archived: false
  forks: true
  exclude:
    forks: false
    projects:
    archived: false
    forks: true

social_media:
  # website: http://utensil.github.io/tech/
  # https://stackoverflow.com/users/200764/utensil
  stackoverflow: 200764
  facebook: utensilsong
  twitter: _utensil_
  linkedin: utensil
  telegram: utensil
  # youtube: UtensilSong
  # medium: @utensilsong
  # behance: utensil
  # dribbble: utensil
  # vk: utensilsong
  # hackerrank: your_username
  # keybase: your_username
  # mastodon: your_username
  # unsplash: your_username

topics:
  - name: Geometric Algebra
    web_url: https://github.com/topics/geometric-algebra
    image_url: https://upload.wikimedia.org/wikipedia/commons/2/27/N_vector_positive.svg
  - name: Rust
    web_url: https://github.com/topics/rust
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/rust/rust.png
  - name: Julia
    web_url: https://github.com/topics/julia
    image_url: https://raw.githubusercontent.com/github/explore/49e13f12be05e7e3f3616bb7a5030d70b259f320/topics/julia/julia.png
