layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    forks: false
    projects:
    # - repo-name

# social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # linkedin: your_username
  # medium: @your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # youtube: your_username
  # vk: your_username

topics:
  - name: Geometric Algebra
    web_url: https://github.com/topics/geometric-algebra
    image_url: https://upload.wikimedia.org/wikipedia/commons/2/27/N_vector_positive.svg
  - name: Rust
    web_url: https://github.com/topics/rust
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/rust/rust.png
